import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Page not found',
	description: 'Generated by create next app',
}

export default function NotFound() {
	return (
		<div className={inter.className}>Page not found</div>
	)
}
